
name: Generate APK
on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.7.2'
      - name: Clean Project
        run: flutter clean
      - name: Run Flutter Doctor
        run: flutter doctor -v
      - name: Fetch pub packages
        run: flutter pub get
      - name: Run Build Runner
        run: flutter pub run build_runner build
      - name: Build APK
        run: flutter build apk
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.ap